/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IxIcon {
        /**
          * Color of the icon
         */
        "color"?: string;
        /**
          * Only fetch and parse svg data when icon is visible
         */
        "lazyLoading": boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "lazy-loading"?: boolean;
        /**
          * Use one of our defined icon names e.g. `copy`  https://ix.siemens.io/docs/icon-library/icons  or the import variant  ``` import { rocket } from '@siemens/ix-icons/icons';  <ix-icon name={rocket}></ix-icon> ```
         */
        "name"?: string;
        /**
          * Size of the icon
         */
        "size": '12' | '16' | '24' | '32';
    }
}
declare global {
    interface HTMLIxIconElement extends Components.IxIcon, HTMLStencilElement {
    }
    var HTMLIxIconElement: {
        prototype: HTMLIxIconElement;
        new (): HTMLIxIconElement;
    };
    interface HTMLElementTagNameMap {
        "ix-icon": HTMLIxIconElement;
    }
}
declare namespace LocalJSX {
    interface IxIcon {
        /**
          * Color of the icon
         */
        "color"?: string;
        /**
          * Only fetch and parse svg data when icon is visible
         */
        "lazyLoading"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "lazy-loading"?: boolean;
        /**
          * Use one of our defined icon names e.g. `copy`  https://ix.siemens.io/docs/icon-library/icons  or the import variant  ``` import { rocket } from '@siemens/ix-icons/icons';  <ix-icon name={rocket}></ix-icon> ```
         */
        "name"?: string;
        /**
          * Size of the icon
         */
        "size"?: '12' | '16' | '24' | '32';
    }
    interface IntrinsicElements {
        "ix-icon": IxIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ix-icon": LocalJSX.IxIcon & JSXBase.HTMLAttributes<HTMLIxIconElement>;
        }
    }
}
