name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/build
      - uses: ./.github/workflows/actions/test
      - name: publish lib
        run: echo yarn publish --tag beta
